#!/usr/bin/env python3
"""Upload Higgsfield-generated monster meshes to Roblox and regenerate AssetIds.

For every monster in assets/manifest.json that has a `model_url` (or a local
file in assets/models/<Id>.glb|.fbx) but no `asset_id`, this downloads the
mesh, uploads it as a Roblox Model through the Open Cloud Assets API, waits
for processing and records the resulting asset id. It then rewrites
src/shared/AssetIds.luau so the game picks the meshes up.

Environment:
  ROBLOX_API_KEY       Open Cloud key with asset:read + asset:write
  ROBLOX_CREATOR_ID    user or group id that owns the experience
  ROBLOX_CREATOR_TYPE  "User" (default) or "Group"

Usage:
  python3 scripts/upload_assets.py            # upload missing + regenerate
  python3 scripts/upload_assets.py --codegen  # only regenerate AssetIds.luau
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
import urllib.error
import urllib.request
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "assets" / "manifest.json"
MODELS_DIR = ROOT / "assets" / "models"
ASSET_IDS_LUAU = ROOT / "src" / "shared" / "AssetIds.luau"

ASSETS_URL = "https://apis.roblox.com/assets/v1/assets"
OPERATIONS_URL = "https://apis.roblox.com/assets/v1/operations/"

CONTENT_TYPES = {
    ".glb": "model/gltf-binary",
    ".gltf": "model/gltf+json",
    ".fbx": "model/fbx",
    ".rbxm": "model/x-rbxm",
}


def load_manifest() -> dict:
    return json.loads(MANIFEST.read_text(encoding="utf-8"))


def save_manifest(manifest: dict) -> None:
    MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def write_asset_ids(manifest: dict) -> None:
    lines = [
        "--!strict",
        "-- GENERATED by scripts/upload_assets.py from assets/manifest.json. Do not edit by hand.",
        "-- Maps monster id -> Roblox Model asset id.",
        "",
        "local AssetIds: { [string]: number } = {",
    ]
    for monster_id, entry in sorted(manifest.get("monsters", {}).items()):
        asset_id = entry.get("asset_id")
        if asset_id:
            lines.append(f"\t{monster_id} = {int(asset_id)},")
    lines += ["}", "", "return AssetIds", ""]
    ASSET_IDS_LUAU.write_text("\n".join(lines), encoding="utf-8")


def read_mesh(monster_id: str, entry: dict) -> tuple[bytes, str] | None:
    for ext in CONTENT_TYPES:
        local = MODELS_DIR / f"{monster_id}{ext}"
        if local.exists():
            return local.read_bytes(), ext
    url = entry.get("model_url")
    if not url:
        return None
    ext = Path(url.split("?")[0]).suffix.lower() or ".glb"
    with urllib.request.urlopen(url, timeout=120) as response:
        return response.read(), ext


def request_json(req: urllib.request.Request) -> dict:
    try:
        with urllib.request.urlopen(req, timeout=120) as response:
            return json.loads(response.read() or b"{}")
    except urllib.error.HTTPError as err:
        body = err.read().decode("utf-8", "replace")
        raise RuntimeError(f"HTTP {err.code} from {req.full_url}: {body}") from err


def upload(monster_id: str, data: bytes, ext: str, api_key: str, creator: dict) -> int:
    request_body = {
        "assetType": "Model",
        "displayName": f"Monster_{monster_id}",
        "description": f"{monster_id} for Steal a Pet Monster (generated with Higgsfield)",
        "creationContext": {"creator": creator},
    }
    boundary = uuid.uuid4().hex
    parts = [
        f"--{boundary}\r\n".encode(),
        b'Content-Disposition: form-data; name="request"\r\n',
        b"Content-Type: application/json\r\n\r\n",
        json.dumps(request_body).encode(),
        f"\r\n--{boundary}\r\n".encode(),
        f'Content-Disposition: form-data; name="fileContent"; filename="{monster_id}{ext}"\r\n'.encode(),
        f"Content-Type: {CONTENT_TYPES.get(ext, 'application/octet-stream')}\r\n\r\n".encode(),
        data,
        f"\r\n--{boundary}--\r\n".encode(),
    ]
    req = urllib.request.Request(
        ASSETS_URL,
        data=b"".join(parts),
        method="POST",
        headers={
            "x-api-key": api_key,
            "Content-Type": f"multipart/form-data; boundary={boundary}",
        },
    )
    operation = request_json(req)
    operation_id = operation.get("operationId") or operation.get("path", "").split("/")[-1]
    if not operation_id:
        raise RuntimeError(f"Unexpected upload response: {operation}")

    for _ in range(60):
        if operation.get("done"):
            break
        time.sleep(3)
        operation = request_json(
            urllib.request.Request(OPERATIONS_URL + operation_id, headers={"x-api-key": api_key})
        )
    if not operation.get("done"):
        raise RuntimeError(f"Upload of {monster_id} did not finish in time (operation {operation_id})")
    if "error" in operation:
        raise RuntimeError(f"Upload of {monster_id} failed: {operation['error']}")
    return int(operation["response"]["assetId"])


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--codegen", action="store_true", help="only regenerate AssetIds.luau")
    args = parser.parse_args()

    manifest = load_manifest()
    if args.codegen:
        write_asset_ids(manifest)
        return 0

    api_key = os.environ.get("ROBLOX_API_KEY")
    creator_id = os.environ.get("ROBLOX_CREATOR_ID")
    if not api_key or not creator_id:
        print("ROBLOX_API_KEY / ROBLOX_CREATOR_ID not set; skipping uploads.")
        write_asset_ids(manifest)
        return 0
    creator_type = os.environ.get("ROBLOX_CREATOR_TYPE", "User").strip().lower()
    creator = {"groupId": creator_id} if creator_type == "group" else {"userId": creator_id}

    failures = 0
    for monster_id, entry in manifest.get("monsters", {}).items():
        if entry.get("asset_id"):
            continue
        mesh = read_mesh(monster_id, entry)
        if not mesh:
            continue
        data, ext = mesh
        print(f"Uploading {monster_id} ({len(data) // 1024} KB, {ext})...")
        try:
            entry["asset_id"] = upload(monster_id, data, ext, api_key, creator)
        except Exception as err:  # keep going so one bad mesh doesn't block the rest
            failures += 1
            print(f"::warning::Upload of {monster_id} failed: {err}", file=sys.stderr)
            continue
        print(f"  -> asset {entry['asset_id']}")
        save_manifest(manifest)

    write_asset_ids(manifest)
    if failures:
        print(f"{failures} upload(s) failed; those monsters keep their placeholder model.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
